#ifndef GUARD_CONSTANTS_FULLY_EVOLVED_MONS_H
#define GUARD_CONSTANTS_FULLY_EVOLVED_MONS_H

#include "constants/species.h"

/*KANTO FULLY EVOLVED MONS*/
const u32 gKantoFullyEvolved[] = {
    /*
    The first three starters are given to the player first through givemon macro, 
    and then the rest are put into the box. This prevents small graphical glitch 
    where player has no pokemon and a question mark icon appears in the pc

    SPECIES_VENUSAUR,
    SPECIES_CHARIZARD,
    SPECIES_BLASTOISE,
    */
    SPECIES_BUTTERFREE,
    SPECIES_BEEDRILL,
    SPECIES_PIDGEOT,
    SPECIES_RATICATE,
    SPECIES_FEAROW,
    SPECIES_ARBOK,
    SPECIES_RAICHU,
    SPECIES_SANDSLASH,
    SPECIES_NIDOQUEEN,
    SPECIES_NIDOKING,
    SPECIES_CLEFABLE,
    SPECIES_NINETALES,
    SPECIES_WIGGLYTUFF,
    SPECIES_VILEPLUME,
    SPECIES_PARASECT,
    SPECIES_VENOMOTH,
    SPECIES_DUGTRIO,
    SPECIES_PERSIAN,
    SPECIES_GOLDUCK,
    SPECIES_ARCANINE,
    SPECIES_POLIWRATH,
    SPECIES_ALAKAZAM,
    SPECIES_MACHAMP,
    SPECIES_VICTREEBEL,
    SPECIES_TENTACRUEL,
    SPECIES_GOLEM,
    SPECIES_RAPIDASH,
    SPECIES_SLOWBRO,
    SPECIES_FARFETCHD,
    SPECIES_DODRIO,
    SPECIES_DEWGONG,
    SPECIES_MUK,
    SPECIES_CLOYSTER,
    SPECIES_GENGAR,
    SPECIES_HYPNO,
    SPECIES_KINGLER,
    SPECIES_ELECTRODE,
    SPECIES_EXEGGUTOR,
    SPECIES_MAROWAK,
    SPECIES_HITMONLEE,
    SPECIES_HITMONCHAN,
    SPECIES_WEEZING,
    SPECIES_KANGASKHAN,
    SPECIES_SEAKING,
    SPECIES_STARMIE,
    SPECIES_MR_MIME,
    SPECIES_JYNX,
    SPECIES_PINSIR,
    SPECIES_TAUROS,
    SPECIES_GYARADOS,
    SPECIES_LAPRAS,
    SPECIES_DITTO,
    SPECIES_VAPOREON,
    SPECIES_JOLTEON,
    SPECIES_FLAREON,
    SPECIES_OMASTAR,
    SPECIES_KABUTOPS,
    SPECIES_AERODACTYL,
    SPECIES_SNORLAX,
};

const u32 gJohtoFullyEvolved[] = {
        SPECIES_MEGANIUM,
    SPECIES_TYPHLOSION,
    SPECIES_FERALIGATR,
    SPECIES_FURRET,
    SPECIES_NOCTOWL,
    SPECIES_LEDIAN,
    SPECIES_ARIADOS,
    SPECIES_CROBAT,
    SPECIES_LANTURN,
    SPECIES_XATU,
    SPECIES_AMPHAROS,
    SPECIES_BELLOSSOM,
    SPECIES_AZUMARILL,
    SPECIES_SUDOWOODO,
    SPECIES_POLITOED,
    SPECIES_JUMPLUFF,
    SPECIES_SUNFLORA,
    SPECIES_QUAGSIRE,
    SPECIES_ESPEON,
    SPECIES_UMBREON,
    SPECIES_SLOWKING,
    SPECIES_UNOWN,
    SPECIES_WOBBUFFET,
    SPECIES_FORRETRESS,
    SPECIES_STEELIX,
    SPECIES_GRANBULL,
    SPECIES_QWILFISH,
    SPECIES_SCIZOR,
    SPECIES_SHUCKLE,
    SPECIES_HERACROSS,
    SPECIES_MAGCARGO,
    SPECIES_CORSOLA,
    SPECIES_OCTILLERY,
    SPECIES_DELIBIRD,
    SPECIES_MANTINE,
    SPECIES_SKARMORY,
    SPECIES_HOUNDOOM,
    SPECIES_KINGDRA,
    SPECIES_DONPHAN,
    SPECIES_SMEARGLE,
    SPECIES_HITMONTOP,
    SPECIES_MILTANK,
    SPECIES_BLISSEY,
    SPECIES_TYRANITAR
};

static const struct MonArrayStruct {
  const u32 *monArray;
  u32 monArrayCount;
} gFullyEvolvedArrays[] = {
    [1] = { gKantoFullyEvolved, ARRAY_COUNT(gKantoFullyEvolved) },
    [2] = { gJohtoFullyEvolved, ARRAY_COUNT(gJohtoFullyEvolved) }
};

#endif //GUARD_CONSTANTS_FULLY_EVOLVED_MONS_H