EventScript_PWTBattleBrock::
# 2 "data/scripts/pwt_scripts.pory"
	trainerbattle_single TRAINER_LEADER_BROCK, EventScript_PWTBattleBrock_Text_0, EventScript_PWTBattleBrock_Text_1
	end


EventScript_PWTBattleMisty::
# 7 "data/scripts/pwt_scripts.pory"
	trainerbattle_single TRAINER_LEADER_MISTY, EventScript_PWTBattleMisty_Text_0, EventScript_PWTBattleMisty_Text_1
	end


EventScript_PWTBattleLtSurge::
# 12 "data/scripts/pwt_scripts.pory"
	trainerbattle_single TRAINER_LEADER_LT_SURGE, EventScript_PWTBattleLtSurge_Text_0, EventScript_PWTBattleLtSurge_Text_1
	end


EventScript_PWTBattleErika::
# 16 "data/scripts/pwt_scripts.pory"
	trainerbattle_single TRAINER_LEADER_ERIKA, EventScript_PWTBattleLtSurge_Text_0, EventScript_PWTBattleLtSurge_Text_1
	end


EventScript_PWTBattleKogaJanine::
# 20 "data/scripts/pwt_scripts.pory"
	trainerbattle_single TRAINER_LEADER_KOGA_AND_JANINE, EventScript_PWTBattleLtSurge_Text_0, EventScript_PWTBattleLtSurge_Text_1
	end


EventScript_PWTBattleSabrina::
# 24 "data/scripts/pwt_scripts.pory"
	trainerbattle_single TRAINER_LEADER_SABRINA, EventScript_PWTBattleLtSurge_Text_0, EventScript_PWTBattleLtSurge_Text_1
	end


EventScript_PWTBattleBlaine::
# 28 "data/scripts/pwt_scripts.pory"
	trainerbattle_single TRAINER_LEADER_BLAINE, EventScript_PWTBattleLtSurge_Text_0, EventScript_PWTBattleLtSurge_Text_1
	end


EventScript_PWTBattleGiovanni::
# 32 "data/scripts/pwt_scripts.pory"
	trainerbattle_single TRAINER_LEADER_GIOVANNI, EventScript_PWTBattleLtSurge_Text_0, EventScript_PWTBattleLtSurge_Text_1
	end


EventScript_PWTBattleBrock_Text_0:
# 2 "data/scripts/pwt_scripts.pory"
	.string "My Pokémon are rock hard!$"

EventScript_PWTBattleBrock_Text_1:
# 2 "data/scripts/pwt_scripts.pory"
	.string "Seems like I've gone soft…$"

EventScript_PWTBattleMisty_Text_0:
# 7 "data/scripts/pwt_scripts.pory"
	.string "Time to make a splash!$"

EventScript_PWTBattleMisty_Text_1:
# 7 "data/scripts/pwt_scripts.pory"
	.string "I can't believe I wiped out!$"

EventScript_PWTBattleLtSurge_Text_0:
# 12 "data/scripts/pwt_scripts.pory"
	.string "This is where it ends!$"

EventScript_PWTBattleLtSurge_Text_1:
# 12 "data/scripts/pwt_scripts.pory"
	.string "It can't end here for me!$"
